# Autogenerated file
def render(name):
    yield """<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
  </head>
  <body>
    <h2>MicroChat</h2>
    
        <form action=\"\" onsubmit=\"sendMessage(event)\">    
            <label>
                Message: <input type=\"text\" id=\"messageText\" autocomplete=\"off\"/>
            </label>
            
            <button>Send</button>
        </form>
        
        <ul id=\"messages\">
        </ul>
    

    <script>
        
        ws = new WebSocket(\"ws://192.168.3.22:5000/ws\");
        
        var name_js = \""""
    yield str(name)
    yield """\";
        
        ws.onmessage = function(event) """
    yield """{
            
            let payload = event.data
            
            const messages = document.getElementById(\"messages\")
            const message = document.createElement(\"li\")
            
            let name_list = event.data.split(\":\");
            let name_only = name_list[0].trim();
            

            
            
            if (name_only == name_js)"""
    yield """{
                
                console.log(\"Passei aqui\")
                payload = payload.replace(name_only, \"you\");  
                
                console.log(payload)
            }
            
            let content = document.createTextNode(payload)
            message.appendChild(content)
            messages.appendChild(message)
            console.log(payload)
            
        }
        
       
        function sendMessage(event)"""
    yield """{
            let inputMsg = document.getElementById(\"messageText\")
            let msg = `"""
    yield """{\"msg\": \"$"""
    yield """{inputMsg.value}\", \"name\": \"$"""
    yield """{name_js}\"}`
            ws.send(msg)
            inputMsg.value = ''
            event.preventDefault()
        }
        
    </script>
    
  </body>
</html>"""
