# Autogenerated file
def render(*a, **d):
    yield """<!DOCTYPE html>
<html lang=\"en\">
  <head>
    <meta charset=\"UTF-8\" />
  </head>
  <body>
    <h1>MicroChat</h1>
    
    <div class=\"container\">  
        <form id=\"formName\" action=\"/chat\" method=\"POST\" >
            
            <label>
                Name: <input type=\"text\" name=\"name\" autocomplete=\"off\"/>
            </label>
            
            <button type=\"submit\">Connect</button>  
        </form>        
    </div>
    
  </body>
</html>
"""
